### ISSUE TITLE
Can webrtc-gun perhaps provide gunDB based signalling for https://github.com/jitsi/jitsi-meet

### ISSUE THREAD

**Issue by mnzaki** [meething/webrtc-gun#8]
https://jitsi.org services are awesome and I think they can be made more awesome with gunDB

They have mature implementations of video conferencing software which can be retrofitted to work with GUN I believe

**Comment by lmangani** [comment]
Hi @mnzaki thanks for the input. 

I personally know some of the Jitsi, Janus and Mediasoup developers since years and I've pitched GUN many times around in our discussions and during conferences. This is unfortunately NOT the case of simply adding signaling to Jitsi or whatever, except for 1:1 calls, as for all of those platforms ship with backend components act as SFU for traffic while the Gun design will be full-mesh p2p. If we add an SFU we centralize things again and beat the purpose of dWeb and browser-to-browser communication without 3rd party resources, but we do have other ideas such as users acting as supernode mixers for others, etc. Will take time and patience :) 

Things will likely shape themselves over time, but for now we are just here to demonstrate a concept alongside other Gun users. Thanks and happy to hear more comments!

**Comment by mnzaki** [comment]
I was trying to read through some discussions on security of conference calls on jitsi, and it looks like p2p mode is indeed disabled for calls with more than 2 participants, which is surprising! So yeah now I'm trying to find details about why they decided to give up on using p2p for conference calls, seems to be out of scalability concerns?
If you can link me to any discussions/materials I would appreciate it :)

But mostly what this issue was about was just that there seems to be a lot of great work that already went into the other projects and it would be a shame to not reuse it :D Anyways, I'm fairly out of my depth here and dunno if it's even possible to reuse much (frontends? native apps?) 

Thanks and keep on hacking!

**Comment by lmangani** [comment]
Thanks! I'm indeed reusing 99% from those projects which I've worked with long (I'm an RTC engineer) - The decisions behind using relays and mcu/sfus for 3+ participants are broad and extremely valid, mostly geared towards requiring the least amount from the weak clients (browsers) and move the complexity to the relay. This might change in the future depending on their evolution.

Best way to help as you did, is try and provide your feedback and motivation, we surely need it!
